const challenges = [    "Learn a new word in a foreign language.",
    "Write a 100-word short story.",
    "Try a new exercise routine for 5 minutes.",
    "Read an article about a topic you’re unfamiliar with.",
    "Practice mindfulness for 10 minutes.",
    "Draw something from memory.",
    "Listen to a podcast on a new subject.",
    "Try cooking a new recipe today.",
    "Spend 10 minutes decluttering a space in your home.",
    "Reflect on a goal you’ve been working on.",
   
"Learn a new word in a foreign language.",  
"Write a 100-word short story.",  
"Try a new exercise routine for 5 minutes.",  
"Read an article about a topic you’re unfamiliar with.",  
"Practice mindfulness for 10 minutes.",  
"Draw something from memory.",  
"Listen to a podcast on a new subject.",  
"Try cooking a new recipe today.",  
"Spend 10 minutes decluttering a space in your home.",  
"Reflect on a goal you’ve been working on.",  
"Call a friend you haven’t talked to in a while.",  
"Spend 15 minutes in nature.",  
"Write down three things you’re grateful for.",  
"Try a new type of tea or coffee.",  
"Do 15 minutes of yoga.",  
"Create a playlist of your favorite songs.",  
"Take a different route on your daily walk.",  
"Learn a new skill using an online tutorial.",  
"Write a letter to your future self.",  
"Practice deep breathing for 5 minutes.",  
"Watch a documentary on a topic you’re curious about.",  
"Organize your email inbox.",  
"Donate unused items to charity.",  
"Spend 20 minutes reading a book.",  
"Try a new form of creative expression, like painting or crafting.",  
"Compliment a stranger.",  
"Make a to-do list for the next week.",  
"Try a new meditation technique.",  
"Write a poem.",  
"Learn a new fact and share it with someone.",  
"Cook a meal using only ingredients you already have.",  
"Create a vision board.",  
"Clean out your fridge.",  
"Spend an hour offline.",  
"Practice positive affirmations.",  
"Take a 20-minute power nap.",  
"Explore a new part of your neighborhood.",  
"Write a handwritten note to someone you appreciate.",  
"Plan your meals for the next three days.",  
"Watch a classic movie you’ve never seen.",  
"Create a budget for the upcoming month.",  
"Try a new hobby for an hour.",  
"Spend 10 minutes stretching.",  
"Organize your digital files.",  
"Make a small change to your daily routine.",  
"Listen to a song from a different culture.",  
"Make a list of your top 5 goals.",  
"Do a random act of kindness.",  
"Take a photo of something that inspires you.",  
"Research a place you’d like to visit.",  
"Spend a day without using any technology.",  

"Start a gratitude journal.",  
"Write down your thoughts before bed.",  
"Try a new breathing technique.",  
"Make a healthy smoothie.",  
"Unfollow social media accounts that don’t inspire you.",  
"Read a poem.",  
"Rearrange the furniture in one room.",  
"Write a list of your strengths.",  
"Plan your dream vacation.",  
"Spend 10 minutes tidying up your space.",  
"Try a new hairstyle.",  
"Watch a TED Talk on a topic you know nothing about.",  
"Take a break from social media for a day.",  
"Write a thank-you note to someone who has helped you.",  
"Make a playlist of relaxing music.",  
"Read the biography of someone you admire.",  
"Learn about a different culture.",  
"Try a new form of exercise.",  
"Write down a plan for achieving one of your goals.",  
"Spend time doing a creative activity.",  
"Take a long walk without any digital distractions.",  
"Try a new type of food.",  
"Write down your dreams after waking up.",  
"Plan a fun activity for the weekend.",  
"Watch the sunrise or sunset.",  
"Research a new topic of interest.",  
"Create a self-care routine.",  
"Organize your closet.",  
"Try a new tea or coffee flavor.",  
"Write a short story based on a dream you’ve had.",  
"Learn how to cook a dish from a different culture.",  
"Plan and prepare a full three-course meal by yourself.",  

"Plan a day trip to a nearby location.",  
"Create a morning routine.",  
"Write a list of books you want to read.",  
"Spend time with a pet or in nature.",  
"Learn a new dance move.",  
"Watch a foreign film.",  
"Take 10 minutes to stretch and move your body.",  
"Make a vision board of your goals.",  
"Practice gratitude by writing down what you're thankful for.",  
"Try a new dessert recipe.",  
"Write a list of things that make you happy.",  
"Take a day to disconnect from technology.",  
"Research a new hobby or interest.",  
"Plan a future vacation.",  
"Spend 10 minutes meditating on your goals.",  
"Write a letter to someone you admire.",  
"Create a bucket list.",  
"Try a new type of exercise or sport.",  
"Listen to a new podcast episode.",  
"Cook a new recipe.",  
"Write down your thoughts and feelings.",  
"Spend time outdoors.",  
"Read a chapter of a book.",  
"Write down your goals for the week.",  
"Practice deep breathing exercises.",  
"Do a random act of kindness for a stranger.",  
"Spend a day volunteering for a cause you care about.",

"Spend time with a loved one.",  
"Watch a documentary.",  
"Try a new type of food.",  
"Write a letter to your future self.",  
"Plan a day trip.",  
"Create a vision board.",  
"Spend time with your pet.",  
"Write a list of things you're grateful for.",  
"Watch a classic movie.",  
"Try a new hobby.",  
"Plan a healthy meal.",  
"Write a letter to someone you love.",  
"Practice a new skill.",  
"Spend time in nature.",  
"Read a self-help book.",  
"Write down your goals.",  
"Plan a future project.",  
"Watch a motivational video.",  
"Try a new recipe.",  
"Write a letter to yourself.",  
"Spend time with family.",  
"Practice a new language.",  
"Read a book on a new subject.",  
"Write down your thoughts and feelings.",  
"Spend time with friends.",  
"Spend an entire day without speaking.",

"Watch a new TV show.",  
"Try a new activity.",  
"Write a letter to a friend.",  
"Spend time with a loved one.",  
"Practice meditation.",  
"Read a new book.",  
"Write down your goals.",  
"Plan a future trip.",  
"Watch a movie.",  
"Try a new hobby.",  
"Write a letter to yourself.",  
"Spend time in nature.",  
"Read a motivational book.",  
"Write down your thoughts and feelings.",  
"Spend time with family.",  
"Practice a new language.",  
"Read a book on a new subject.",  
"Write a letter to a friend.",  
"Spend time with friends.",  
"Watch a new TV show.",  
"Try a new activity.",  
"Write a letter to a loved one.",  
"Practice meditation.",  
"Read a new book.",  
"Write down your goals.",  
"Plan an entire week of meals and activities.",

"Watch a movie.",  
"Try a new hobby.",  
"Write a letter to yourself.",  
"Spend time in nature.",  
"Read a motivational book.",  
"Write down your thoughts and feelings.",  
"Spend time with family.",  
"Practice a new language.",  
"Read a book on a new subject.",  
"Write a letter to a friend.",  
"Spend time with friends.",  
"Watch a new TV show.",  
"Try a new activity.",  
"Write a letter to a loved one.",  
"Practice meditation.",  
"Read a new book.",  
"Write down your goals.",  
"Plan a future trip.",  
"Watch a movie.",  
"Try a new hobby.",  
"Write a letter to yourself.",  
"Spend time in nature.",  
"Read a motivational book.",  
"Write down your thoughts and feelings.",  
"Spend an entire day on personal reflection and self-improvement."
 
];

document.getElementById('spin-button').addEventListener('click', () => {
    const wheel = document.getElementById('wheel');
    const randomAngle = Math.floor(Math.random() * 360) + 720; // Spin at least two full rotations
    const selectedSegment = Math.floor(((randomAngle % 360) / 36)); // There are 10 segments, each 36 degrees
    const selectedChallenge = challenges[selectedSegment];
    
    wheel.style.transform = `rotate(${randomAngle}deg)`;

    setTimeout(() => {
        document.getElementById('challenge-text').textContent = selectedChallenge;
        document.getElementById('challenge-card').style.display = 'block';
    }, 4000); // Display the challenge after the spin ends
});
